
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  7 2025 17:08:23 IST (Mar  7 2025 11:38:23 UTC)

// Verification Directory fv/mcrb 

module mcrb(mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, skew_addr_cntr_o,
     mc_rb_fuse_vld_i, mc_rb_ef1_sclk_i);
  input mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  output [4:0] skew_addr_cntr_o;
  wire mc_rb_ef1_svld_i, gctl_rclk_orst_n_i, mc_rb_fuse_vld_i,
       mc_rb_ef1_sclk_i;
  wire [4:0] skew_addr_cntr_o;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, mc_rb_fuse_vld_q, n_0;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  DFFR_X2 \skew_addr_cntr_reg[4] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_16), .Q (skew_addr_cntr_o[4]), .QN
       (UNCONNECTED));
  AND2_X2 g426__2398(.A1 (n_15), .A2 (n_13), .ZN (n_16));
  DFFR_X1 \skew_addr_cntr_reg[3] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_14), .Q (skew_addr_cntr_o[3]), .QN
       (UNCONNECTED0));
  XOR2_X1 g428__5107(.A (n_11), .B (skew_addr_cntr_o[4]), .Z (n_15));
  DFFR_X2 \skew_addr_cntr_reg[0] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_10), .Q (skew_addr_cntr_o[0]), .QN
       (UNCONNECTED1));
  AND2_X2 g429__6260(.A1 (n_13), .A2 (n_12), .ZN (n_14));
  DFFR_X2 \skew_addr_cntr_reg[1] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_9), .Q (skew_addr_cntr_o[1]), .QN
       (UNCONNECTED2));
  DFFR_X1 \skew_addr_cntr_reg[2] (.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (n_8), .Q (skew_addr_cntr_o[2]), .QN
       (UNCONNECTED3));
  HA_X1 g430__4319(.A (n_5), .B (skew_addr_cntr_o[3]), .CO (n_11), .S
       (n_12));
  NOR2_X2 g434__8428(.A1 (n_7), .A2 (skew_addr_cntr_o[0]), .ZN (n_10));
  AND2_X4 g435__5526(.A1 (n_13), .A2 (n_3), .ZN (n_9));
  AND2_X2 g436__6783(.A1 (n_13), .A2 (n_6), .ZN (n_8));
  INV_X1 g437(.A (n_13), .ZN (n_7));
  OAI21_X2 g438__3680(.A (n_4), .B1 (mc_rb_ef1_svld_i), .B2
       (mc_rb_fuse_vld_q), .ZN (n_13));
  HA_X1 g439__1617(.A (n_2), .B (skew_addr_cntr_o[2]), .CO (n_5), .S
       (n_6));
  MUX2_X1 g440__2802(.A (n_1), .B (n_0), .S (skew_addr_cntr_o[4]), .Z
       (n_4));
  HA_X1 g442__1705(.A (skew_addr_cntr_o[1]), .B (skew_addr_cntr_o[0]),
       .CO (n_2), .S (n_3));
  NOR3_X2 g441__5122(.A1 (n_0), .A2 (skew_addr_cntr_o[0]), .A3
       (skew_addr_cntr_o[1]), .ZN (n_1));
  DFFR_X1 mc_rb_fuse_vld_q_reg(.RN (gctl_rclk_orst_n_i), .CK
       (mc_rb_ef1_sclk_i), .D (mc_rb_fuse_vld_i), .Q (UNCONNECTED4),
       .QN (mc_rb_fuse_vld_q));
  OR2_X2 g444__8246(.A1 (skew_addr_cntr_o[3]), .A2
       (skew_addr_cntr_o[2]), .ZN (n_0));
endmodule

