
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Mar  7 2025 16:24:15 IST (Mar  7 2025 10:54:15 UTC)

// Verification Directory fv/s298 

module dff(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  CDN_flop q_reg(.clk (clk), .d (d), .sena (1'b1), .aclr (1'b0), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (q));
endmodule

module dff_26(clk, q, d);
  input clk, d;
  output q;
  wire clk, d;
  wire q;
  CDN_flop q_reg(.clk (clk), .d (d), .sena (1'b1), .aclr (1'b0), .apre
       (1'b0), .srl (1'b0), .srd (1'b0), .q (q));
endmodule

module s298(GND, VDD, CK, G0, G1, G117, G118, G132, G133, G2, G66, G67);
  input GND, VDD, CK, G0, G1, G2;
  output G117, G118, G132, G133, G66, G67;
  wire GND, VDD, CK, G0, G1, G2;
  wire G117, G118, G132, G133, G66, G67;
  wire G10, G11, G12, G13, G14, G15, G22, G23;
  wire G29, G30, G34, G39, G44, G56, G86, G92;
  wire G98, G102, G107, G113, G119, G125, n_39, n_58;
  wire n_75, n_83, n_132, n_142, n_145, n_148, n_151, n_155;
  wire n_156, n_157, n_160, n_161, n_162, n_163, n_164, n_165;
  wire n_166, n_167, n_168, n_171, n_174, n_179, n_180, n_185;
  wire n_186, n_191, n_192, n_195, n_202, n_203, n_204, n_213;
  wire n_214, n_215, n_216, n_225, n_226, n_227, n_228, n_231;
  wire n_238, n_239, n_240, n_243, n_250, n_251, n_252, n_261;
  wire n_262, n_263, n_264, n_269, n_270, n_275, n_276, n_281;
  wire n_282, n_290, n_291, n_293, n_294, n_297, n_298, n_299;
  wire n_300;
  dff DFF_0(CK, G10, G29);
  dff_26 DFF_1(CK, G11, G30);
  dff_26 DFF_2(CK, G12, G34);
  dff_26 DFF_3(CK, G13, G39);
  dff_26 DFF_4(CK, G14, G44);
  dff_26 DFF_5(CK, G15, G56);
  dff DFF_6(CK, G66, G86);
  dff DFF_7(CK, G67, G92);
  dff DFF_8(CK, G117, G98);
  dff DFF_9(CK, G118, G102);
  dff DFF_10(CK, G132, G107);
  dff DFF_11(CK, G133, G113);
  dff DFF_12(CK, G22, G119);
  dff DFF_13(CK, G23, G125);
  or g96 (n_39, G12, wc);
  not gc (wc, G13);
  nand g352 (n_142, G10, G11);
  or g443 (n_157, G12, G13);
  or g450 (n_156, wc0, G11);
  not gc0 (wc0, G22);
  or g475 (n_164, n_156, G12);
  or g548 (G107, n_251, wc1);
  not gc1 (wc1, n_252);
  or g551 (G102, n_75, n_264);
  or g552 (n_252, wc2, G10);
  not gc2 (wc2, n_83);
  or g555 (G86, n_75, wc3);
  not gc3 (wc3, n_243);
  or g558 (n_264, wc4, n_263);
  not gc4 (wc4, n_262);
  or g559 (n_166, n_227, wc5);
  not gc5 (wc5, n_228);
  nand g560 (n_83, n_239, n_240);
  or g561 (G92, wc6, n_216);
  not gc6 (wc6, n_215);
  or g562 (G98, wc7, n_282);
  not gc7 (wc7, n_281);
  nand g565 (n_282, n_151, n_214);
  nand g566 (n_263, n_261, n_155);
  nand g567 (n_251, n_155, n_250);
  nand g568 (n_228, n_165, G12);
  or g569 (n_290, wc8, G14);
  not gc8 (wc8, n_145);
  or g570 (n_291, n_145, wc9);
  not gc9 (wc9, G14);
  nand g571 (n_162, n_290, n_291);
  nand g572 (n_75, n_148, n_270);
  nand g573 (n_239, n_148, G15);
  nand g574 (G113, n_203, n_204);
  nand g575 (n_216, n_213, n_214);
  or g576 (n_148, n_192, n_39);
  or g577 (n_214, n_132, wc10);
  not gc10 (wc10, G11);
  or g578 (n_215, n_58, wc11);
  not gc11 (wc11, G67);
  or g579 (n_213, n_151, G11);
  or g580 (n_155, n_231, n_132);
  or g581 (n_204, n_202, n_151);
  or g582 (n_243, n_58, wc12);
  not gc12 (wc12, G66);
  or g583 (n_203, n_58, wc13);
  not gc13 (wc13, G133);
  nand g584 (n_227, n_225, n_226);
  nand g585 (n_165, n_185, n_186);
  or g586 (n_270, wc14, n_269);
  not gc14 (wc14, n_164);
  or g587 (n_240, n_39, n_238);
  or g588 (n_250, n_58, wc15);
  not gc15 (wc15, G132);
  or g589 (n_261, wc16, G10);
  not gc16 (wc16, n_163);
  or g590 (n_262, n_58, wc17);
  not gc17 (wc17, G118);
  nand g591 (n_168, n_275, n_276);
  or g592 (n_281, n_58, wc18);
  not gc18 (wc18, G117);
  or g593 (n_145, G23, wc19);
  not gc19 (wc19, n_180);
  nand g596 (n_293, n_142, G12);
  or g597 (n_294, n_142, G12);
  nand g598 (n_167, n_293, n_294);
  or g599 (n_275, n_179, wc20);
  not gc20 (wc20, n_39);
  or g600 (n_163, G15, wc21);
  not gc21 (wc21, n_171);
  or g601 (n_151, G15, n_174);
  or g602 (n_132, n_157, G15);
  or g603 (n_185, n_142, G13);
  or g604 (n_238, G14, n_156);
  or g605 (n_226, n_39, wc22);
  not gc22 (wc22, G11);
  or g608 (n_58, n_195, wc23);
  not gc23 (wc23, n_157);
  or g609 (n_269, G15, n_171);
  or g612 (n_180, n_179, n_39);
  or g613 (n_192, G14, n_191);
  or g614 (n_297, wc24, G23);
  not gc24 (wc24, G1);
  or g615 (n_298, G1, wc25);
  not gc25 (wc25, G23);
  nand g616 (n_161, n_297, n_298);
  or g617 (n_179, G11, wc26);
  not gc26 (wc26, G10);
  or g618 (n_299, wc27, G22);
  not gc27 (wc27, G2);
  or g619 (n_300, G2, wc28);
  not gc28 (wc28, G22);
  nand g620 (n_160, n_299, n_300);
  or g621 (n_225, G10, wc29);
  not gc29 (wc29, G13);
  or g622 (n_186, G11, wc30);
  not gc30 (wc30, G13);
  or g623 (n_276, G10, wc31);
  not gc31 (wc31, G11);
  or g624 (n_171, G14, wc32);
  not gc32 (wc32, G13);
  or g625 (n_174, G13, G14);
  or g626 (n_195, wc33, G15);
  not gc33 (wc33, G14);
  nand g627 (n_202, G11, G12);
  or g628 (n_231, G11, wc34);
  not gc34 (wc34, G14);
  or g629 (n_191, wc35, G22);
  not gc35 (wc35, G11);
  nor g632 (G29, G0, G10);
  and g633 (G119, wc36, n_160);
  not gc36 (wc36, G0);
  and g634 (G125, wc37, n_161);
  not gc37 (wc37, G0);
  and g635 (G30, wc38, n_168);
  not gc38 (wc38, G0);
  and g636 (G34, wc39, n_167);
  not gc39 (wc39, G0);
  and g637 (G39, wc40, n_166);
  not gc40 (wc40, G0);
  and g638 (G56, wc41, n_83);
  not gc41 (wc41, G0);
  and g639 (G44, wc42, n_162);
  not gc42 (wc42, G0);
endmodule

`ifdef RC_CDN_GENERIC_GATE
`else
module CDN_flop(clk, d, sena, aclr, apre, srl, srd, q);
  input clk, d, sena, aclr, apre, srl, srd;
  output q;
  wire clk, d, sena, aclr, apre, srl, srd;
  wire q;
  reg  qi;
  assign #1 q = qi;
  always 
    @(posedge clk or posedge apre or posedge aclr) 
      if (aclr) 
        qi <= 0;
      else if (apre) 
          qi <= 1;
        else if (srl) 
            qi <= srd;
          else begin
            if (sena) 
              qi <= d;
          end
  initial 
    qi <= 1'b0;
endmodule
`endif
